local M = {}

M.should_open = false

M.project_markers = {
  ".git",
  ".hg",
  ".svn",
  "Makefile",
  "CMakeLists.txt",
  "README.md",
  ".editorconfig",
  "docker-compose.yml",
  "Dockerfile",
  "package.json",
  "tsconfig.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "deno.json",
  "Cargo.toml",
  "go.mod",
  "go.work",
  "pyproject.toml",
  "requirements.txt",
  "setup.py",
  "Pipfile",
  "poetry.lock",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "Gemfile",
  "composer.json",
  "pubspec.yaml",
  "Package.swift",
  "Podfile",
  "build.zig",
  "*.sln",
  "*.csproj",
}
return M
