local M = {}
local utils = require("core.utils")

M.enabled_servers = {
  "nil_ls",
  "emmylua_ls",
  "lua_ls",
  "pyright",
  -- "basedpyright",
  "ruff",
  "bashls",
  "taplo",
  "jsonls",
  "java",
  "jdtls",
}

M.kind_icons = {
  TabNine = "",
  Copilot = "",
  Snippet = "",
  claude = "󰋦",
  openai = "󱢆",
  codestral = "󱎥",
  gemini = "",
  Groq = "",
  Openrouter = "󱂇",
  Ollama = "󰳆",
  ["Llama.cpp"] = "󰳆",
  Deepseek = "",
}

M.kind_menus = {
  nvim_lsp = "[LSP]",
  luasnip = "[Snippet]",
  buffer = "[Buf]",
  path = "[Path]",
  cmp_tabnine = "[TN]",
  copilot = "[Co]",
  cmdline = "[CMD]",
  dap = "[DAP]",
  nvim_lsp_signature_help = "[SIG]",
  tmux = "[TMUX]",
  codecompanion = "[CC]",
}
M.kind_presets = {
  default = {
    -- if you change or add symbol here
    -- replace corresponding line in readme
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰊕",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "",
  },
  codicons = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
  Text = true,
  Method = true,
  Function = true,
  Constructor = true,
  Field = true,
  Variable = true,
  Class = true,
  Interface = true,
  Module = true,
  Property = true,
  Unit = true,
  Value = true,
  Enum = true,
  Keyword = true,
  Snippet = true,
  Color = true,
  File = true,
  Reference = true,
  Folder = true,
  EnumMember = true,
  Constant = true,
  Struct = true,
  Event = true,
  Operator = true,
  TypeParameter = true,
}

return M
